name: Trigger Update Metadata
on:
  push:
    paths:
      - meta/**
  workflow_dispatch:

jobs:
  TriggerUpdateMetadata:
    uses:
      NightmareXIV/MyDalamudPlugins/.github/workflows/Update_Metadata.yml@main
    secrets: inherit
